spring:
  r2dbc:
    host: localhost
    port: 3306
    db: autenticacion
    url: r2dbc:mysql://localhost:3306/autenticacion
    username: root
    password: 1234
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: DEBUG